import pandas as pd
import numpy as np
import matplotlib as pll
import ast
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [1]:
import pandas as pd
import numpy as np
import matplotlib as pll
import ast
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [5]:
df = pd.read_csv("C:\\Users\\Olamide\\Desktop\\MY STREAMLIT CLASS\\Level_5_project//customers.csv")
df2 = pd.read_csv("C:\\Users\\Olamide\\Desktop\\MY STREAMLIT CLASS\\Level_5_project//events.csv")
df3 = pd.read_csv("C:\\Users\\Olamide\\Desktop\\MY STREAMLIT CLASS\\Level_5_project//offers.csv")
print(df2.head(20))
print(df3.info())

                         customer_id           event  \
0   78afa995795e4d85b5d9ceeca43f5fef  offer received
1   a03223e636434f42ac4c3df47e8bac43  offer received
2   e2127556f4f64592b11af22de27a7932  offer received
3   8ec6ce2a7e7949b1bf142def7d0e0586  offer received
4   68617ca6246f4fbc85e91a2a49552598  offer received
5   389bc3fa690240e798340f5a15918d5c  offer received
6   c4863c7985cf408faee930f111475da3  offer received
7   2eeac8d8feae4a8cad5a6af0499a211d  offer received
8   aa4862eba776480b8bb9c68455b8c2e1  offer received
9   31dda685af34476cad5bc968bdb01c53  offer received
10  744d603ef08c4f33af5a61c8c7628d1c  offer received
11  3d02345581554e81b7b289ab5e288078  offer received
12  4b0da7e80e5945209a1fdddfe813dbe0  offer received
13  c27e0d6ab72c455a8bb66d980963de60  offer received
14  d53717f5400c4e84affdaeda9dd926b3  offer received
15  f806632c011441378d4646567f357a21  offer received
16  d058f73bf8674a26a95227db098147b1  offer received
17  65aba5c617294649aeb624da249e1ee5  offer received
18  ebe7ef46ea6f4963a7dd49f501b26779  offer received
19  1e9420836d554513ab90eba98552d0a9  offer received

                                               value  time
0   {'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'}     0
1   {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}     0
2   {'offer id': '2906b810c7d4411798c6938adc9daaa5'}     0
3   {'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'}     0
4   {'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'}     0
5   {'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'}     0
6   {'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'}     0
7   {'offer id': '3f207df678b143eea3cee63160fa8bed'}     0
8   {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}     0
9   {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}     0
10  {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}     0
11  {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}     0
12  {'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'}     0
13  {'offer id': '3f207df678b143eea3cee63160fa8bed'}     0
14  {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}     0
15  {'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'}     0
16  {'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'}     0
17  {'offer id': '2906b810c7d4411798c6938adc9daaa5'}     0
18  {'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'}     0
19  {'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'}     0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
offer_id      10 non-null object
offer_type    10 non-null object
difficulty    10 non-null int64
reward        10 non-null int64
duration      10 non-null int64
channels      10 non-null object
dtypes: int64(3), object(3)
memory usage: 608.0+ bytes
None

In [13]:
df["became_member_on"] = pd.to_datetime(df["became_member_on"], format="%Y%m%d")
df["income"] = df["income"].fillna(df["income"].median())
df = df.drop(columns=["gender"])
df["age"] = df["age"].replace(118, "unknown")

cleaned_path = "cleaned_customer.csv"
df.to_csv(cleaned_path, index=False)

In [6]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 5 columns):
customer_id         17000 non-null object
became_member_on    17000 non-null int64
gender              14825 non-null object
age                 17000 non-null int64
income              14825 non-null float64
dtypes: float64(1), int64(2), object(2)
memory usage: 664.2+ KB
None
                        customer_id  became_member_on gender  age    income
0  68be06ca386d4c31939f3a4f0e3dd783          20170212    NaN  118       NaN
1  0610b486422d4921ae7d2bf64640c50b          20170715      F   55  112000.0
2  38fe809add3b4fcf9315a9694bb96ff5          20180712    NaN  118       NaN
3  78afa995795e4d85b5d9ceeca43f5fef          20170509      F   75  100000.0
4  a03223e636434f42ac4c3df47e8bac43          20170804    NaN  118       NaN

,customer_id,event,value,time
306484,a4c2dd694269444085976f10b9b225f6,transaction,{'amount': 28.58},714
306485,4b59509988d34c7298119a840c946453,transaction,{'amount': 0.06},714
306486,92153f7cdda8486b9a2214ceb11b1a17,transaction,{'amount': 4.39},714
306487,3c88696ac23741cb8a709d656fe5ccdf,transaction,{'amount': 25.76},714
306488,1b24e887d980450497b631d8756128e6,transaction,{'amount': 0.35000000000000003},714
306489,1c71315203b746b786c43ce12d7e97fe,transaction,{'amount': 20.84},714
306490,abc4359eb34e4e2ca2349da2ddf771b6,offer viewed,{'offer id': '3f207df678b143eea3cee63160fa8bed'},714
306491,693082e8ccf9458a88c428779cf556a6,transaction,{'amount': 2.16},714
306492,d4f6205a98b4420082aae16e5a93655a,transaction,{'amount': 1.22},714
306493,7b2939e61c324b2087328c4b6fee2632,transaction,{'amount': 26.41},714
306494,e110e63527c24ad1b482f76acde24a42,transaction,{'amount': 20.89},714
306495,5bc03149267147edbcd6a778742b708b,transaction,{'amount': 32.23},714
306496,a6f84f4e976f44508c358cc9aba6d2b3,transaction,{'amount': 6.49},714
306497,a6f84f4e976f44508c358cc9aba6d2b3,offer completed,{'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2...,714
306498,a62b73003f084ae4ae59c4b0e617f647,transaction,{'amount': 19.03},714
306499,197a4afbf77245cfa84c0a4659f47c48,transaction,{'amount': 25.65},714
306500,f0ffaed9279946f1bc29614a234f1ee1,transaction,{'amount': 1.43},714
306501,93907d06a946424ba630487fe7aeafd1,transaction,{'amount': 28.03},714
306502,588ceea482344c3ab6845c83aaed4ac0,transaction,{'amount': 1.08},714
306503,a97208c5be42445d9949e82e0f70f622,transaction,{'amount': 5.8},714
306504,8524d450673b4c24869b6c94380006de,transaction,{'amount': 4.89},714
306505,b895c57e8cd047a8872ce02aa54759d6,transaction,{'amount': 4.48},714
306506,b895c57e8cd047a8872ce02aa54759d6,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714
306507,8dda575c2a1d44b9ac8e8b07b93d1f8e,offer viewed,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},714
306508,8431c16f8e1d440880db371a68f82dd0,transaction,{'amount': 1.19},714
306509,8431c16f8e1d440880db371a68f82dd0,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714
306510,ba620885e51c4b0ea64a4f61daad494f,transaction,{'amount': 14.31},714
306511,a1a8f40407c444cc848468275308958a,transaction,{'amount': 2.37},714
306512,8d80970192fa496f99d6b45c470a4b60,transaction,{'amount': 6.92},714
306513,bde275066f3c4fa0bff3093e3b866a2c,transaction,{'amount': 12.73},714
306514,f1e4fd36e5a0446f83861308bddf6945,transaction,{'amount': 8.2},714
306515,0b64be3b241c4407a5c9a71781173829,transaction,{'amount': 2.6},714
306516,86d03d35d7e0434b935e7743e83be3a0,transaction,{'amount': 9.2},714
306517,3408fd05c781401f8442fb6dbaaea9c7,transaction,{'amount': 11.7},714
306518,1593d617fac246ef8e50dbb0ffd77f5f,transaction,{'amount': 40.67},714
306519,f1b31d07b5d84f69a2d5f1d07843989e,transaction,{'amount': 31.13},714
306520,2ce987015ec0404a97ba333e8e814090,transaction,{'amount': 1.6400000000000001},714
306521,2e33545f0a764d27b2ccff95fc8d72c4,transaction,{'amount': 17.35},714
306522,d1c4500ace2e45e9a45d3cd2fccac8d8,transaction,{'amount': 4.42},714
306523,b65affd9e07346a1906364a396950e3d,transaction,{'amount': 18.35},714
306524,d613ca9c59dd42f497bdbf6178da54a7,transaction,{'amount': 25.14},714
306525,eec70ab28af74a22a4aeb889c0317944,transaction,{'amount': 43.58},714
306526,24f56b5e1849462093931b164eb803b5,transaction,{'amount': 22.64},714
306527,24f56b5e1849462093931b164eb803b5,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714
306528,5ca2620962114246ab218fc648eb3934,transaction,{'amount': 2.2},714
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.5899999999999999},714
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714
306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.5300000000000002},714
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714

In [20]:
df["age"].min()

In [11]:


# 1️⃣ Standardize column names
df3.columns = df3.columns.str.strip().str.lower().str.replace(" ", "_")

# 2️⃣ Remove duplicates
df3.drop_duplicates(inplace=True)

# 3️⃣ Convert numeric columns to proper types
numeric_cols = ['difficulty', 'reward', 'duration']
for col in numeric_cols:
    if col in df3.columns:
        df3[col] = pd.to_numeric(df3[col], errors='coerce')

# 4️⃣ Safely parse 'channels' column
def safe_parse_channels(x):
    if isinstance(x, str) and x.startswith('['):  # list-like string
        try:
            return ast.literal_eval(x)
        except:
            return []
    elif isinstance(x, list):  # already a list
        return x
    else:
        return []  # handle NaN or anything unexpected

if 'channels' in df3.columns:
    df3['channels'] = df3['channels'].apply(safe_parse_channels)

# 5️⃣ Find all unique channels
unique_channels = sorted({ch for sublist in df3['channels'] if isinstance(sublist, list) for ch in sublist})

# 6️⃣ Create Yes/No indicator columns for each channel
for ch in unique_channels:
    df3[ch] = df3['channels'].apply(lambda x: 'Yes' if ch in x else 'No')
df3['channels'] = df3['channels'].apply(lambda x: ', '.join(x) if isinstance(x, list) else '')
text_cols = ['offer_id', 'offer_type']
for col in text_cols:
    if col in df3.columns:
        df3[col] = df3[col].astype(str).str.strip().str.lower()


cleaned_path = "cleaned_offers.csv"
df3.to_csv(cleaned_path, index=False)

In [47]:
print(df3.info())
print(df3.head(85))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   offer_id    10 non-null     object
 1   offer_type  10 non-null     object
 2   difficulty  10 non-null     int64
 3   reward      10 non-null     int64
 4   duration    10 non-null     int64
 5   channels    10 non-null     object
 6   email       10 non-null     object
 7   mobile      10 non-null     object
 8   social      10 non-null     object
 9   web         10 non-null     object
dtypes: int64(3), object(7)
memory usage: 880.0+ bytes
None
                           offer_id     offer_type  difficulty  reward  \
0  ae264e3637204a6fb9bb56bc8210ddfd           bogo          10      10
1  4d5c57ea9a6940dd891ad53e9dbe8da0           bogo          10      10
2  3f207df678b143eea3cee63160fa8bed  informational           0       0
3  9b98b8c7a33c4b65b9aebfe6a799e6d9           bogo           5       5
4  0b1e1539f2cc45b7b9fa7c272da2e1d7       discount          20       5
5  2298d6c36e964ae4a3e7e9706d1fb8c2       discount           7       3
6  fafdcd668e3743c1bb461111dcafc2a4       discount          10       2
7  5a8bc65990b245e5a138643cd4eb9837  informational           0       0
8  f19421c1d4aa40978ebb69ca19b0e20d           bogo           5       5
9  2906b810c7d4411798c6938adc9daaa5       discount          10       2

   duration channels email mobile social  web
0         7            Yes    Yes    Yes   No
1         5            Yes    Yes    Yes  Yes
2         4            Yes    Yes     No  Yes
3         7            Yes    Yes     No  Yes
4        10            Yes     No     No  Yes
5         7            Yes    Yes    Yes  Yes
6        10            Yes    Yes    Yes  Yes
7         3            Yes    Yes    Yes   No
8         5            Yes    Yes    Yes  Yes
9         7            Yes    Yes     No  Yes

In [2]:
# df2 = pd.read_csv("C:\\Users\\Olamide\\Desktop\\MY STREAMLIT CLASS\\Level_5_project//events.csv")

In [4]:
import pandas as pd
import ast

# --- 1. Load and Clean Column Names ---
df2 = pd.read_csv('events.csv')

# Clean column names (lowercase, replace spaces with underscores)
df2.columns = df2.columns.str.strip().str.lower().str.replace(" ", "_")


# --- 2. Safely Convert 'value' Column to Dictionary ---

def safe_to_dict(x):
    """Safely converts a stringified Python literal (dict) to a dict object."""
    if isinstance(x, str) and x.startswith("{"):
        try:
            # ast.literal_eval is used to safely parse the dictionary string
            return ast.literal_eval(x)
        except:
            return {}
    return {}

# Apply the conversion function
df2['value'] = df2['value'].apply(safe_to_dict)

# --- 3. Extract Key/Value Pairs into New Columns ---
# The two most important key/value pairs are 'offer id' and 'amount'.

# A. Extract 'offer_id' (handles both 'offer id' and 'offer_id' keys)
df2['offer_id'] = df2['value'].apply(lambda d: d.get('offer id') or d.get('offer_id'))

# B. Extract 'amount'
df2['amount'] = df2['value'].apply(lambda d: d.get('amount'))

# C. Convert amount to numeric for filtering/calculations
df2['amount'] = pd.to_numeric(df2['amount'], errors='coerce')


# --- 4. Save the Result ---
df2.to_csv('cleaned_events_finally.csv', index=False)

In [3]:
df2.tail(50)
# print(df2.info())
# print(df2.head(85))

,customer_id,event,value,time,offer_id,amount
306484,a4c2dd694269444085976f10b9b225f6,transaction,{'amount': 28.58},714,None,28.58
306485,4b59509988d34c7298119a840c946453,transaction,{'amount': 0.06},714,None,0.06
306486,92153f7cdda8486b9a2214ceb11b1a17,transaction,{'amount': 4.39},714,None,4.39
306487,3c88696ac23741cb8a709d656fe5ccdf,transaction,{'amount': 25.76},714,None,25.76
306488,1b24e887d980450497b631d8756128e6,transaction,{'amount': 0.35000000000000003},714,None,0.35
306489,1c71315203b746b786c43ce12d7e97fe,transaction,{'amount': 20.84},714,None,20.84
306490,abc4359eb34e4e2ca2349da2ddf771b6,offer viewed,{'offer id': '3f207df678b143eea3cee63160fa8bed'},714,3f207df678b143eea3cee63160fa8bed,NaN
306491,693082e8ccf9458a88c428779cf556a6,transaction,{'amount': 2.16},714,None,2.16
306492,d4f6205a98b4420082aae16e5a93655a,transaction,{'amount': 1.22},714,None,1.22
306493,7b2939e61c324b2087328c4b6fee2632,transaction,{'amount': 26.41},714,None,26.41
306494,e110e63527c24ad1b482f76acde24a42,transaction,{'amount': 20.89},714,None,20.89
306495,5bc03149267147edbcd6a778742b708b,transaction,{'amount': 32.23},714,None,32.23
306496,a6f84f4e976f44508c358cc9aba6d2b3,transaction,{'amount': 6.49},714,None,6.49
306497,a6f84f4e976f44508c358cc9aba6d2b3,offer completed,{'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2...,714,2298d6c36e964ae4a3e7e9706d1fb8c2,NaN
306498,a62b73003f084ae4ae59c4b0e617f647,transaction,{'amount': 19.03},714,None,19.03
306499,197a4afbf77245cfa84c0a4659f47c48,transaction,{'amount': 25.65},714,None,25.65
306500,f0ffaed9279946f1bc29614a234f1ee1,transaction,{'amount': 1.43},714,None,1.43
306501,93907d06a946424ba630487fe7aeafd1,transaction,{'amount': 28.03},714,None,28.03
306502,588ceea482344c3ab6845c83aaed4ac0,transaction,{'amount': 1.08},714,None,1.08
306503,a97208c5be42445d9949e82e0f70f622,transaction,{'amount': 5.8},714,None,5.80
306504,8524d450673b4c24869b6c94380006de,transaction,{'amount': 4.89},714,None,4.89
306505,b895c57e8cd047a8872ce02aa54759d6,transaction,{'amount': 4.48},714,None,4.48
306506,b895c57e8cd047a8872ce02aa54759d6,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,fafdcd668e3743c1bb461111dcafc2a4,NaN
306507,8dda575c2a1d44b9ac8e8b07b93d1f8e,offer viewed,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},714,0b1e1539f2cc45b7b9fa7c272da2e1d7,NaN
306508,8431c16f8e1d440880db371a68f82dd0,transaction,{'amount': 1.19},714,None,1.19
306509,8431c16f8e1d440880db371a68f82dd0,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,fafdcd668e3743c1bb461111dcafc2a4,NaN
306510,ba620885e51c4b0ea64a4f61daad494f,transaction,{'amount': 14.31},714,None,14.31
306511,a1a8f40407c444cc848468275308958a,transaction,{'amount': 2.37},714,None,2.37
306512,8d80970192fa496f99d6b45c470a4b60,transaction,{'amount': 6.92},714,None,6.92
306513,bde275066f3c4fa0bff3093e3b866a2c,transaction,{'amount': 12.73},714,None,12.73
306514,f1e4fd36e5a0446f83861308bddf6945,transaction,{'amount': 8.2},714,None,8.20
306515,0b64be3b241c4407a5c9a71781173829,transaction,{'amount': 2.6},714,None,2.60
306516,86d03d35d7e0434b935e7743e83be3a0,transaction,{'amount': 9.2},714,None,9.20
306517,3408fd05c781401f8442fb6dbaaea9c7,transaction,{'amount': 11.7},714,None,11.70
306518,1593d617fac246ef8e50dbb0ffd77f5f,transaction,{'amount': 40.67},714,None,40.67
306519,f1b31d07b5d84f69a2d5f1d07843989e,transaction,{'amount': 31.13},714,None,31.13
306520,2ce987015ec0404a97ba333e8e814090,transaction,{'amount': 1.6400000000000001},714,None,1.64
306521,2e33545f0a764d27b2ccff95fc8d72c4,transaction,{'amount': 17.35},714,None,17.35
306522,d1c4500ace2e45e9a45d3cd2fccac8d8,transaction,{'amount': 4.42},714,None,4.42
306523,b65affd9e07346a1906364a396950e3d,transaction,{'amount': 18.35},714,None,18.35
306524,d613ca9c59dd42f497bdbf6178da54a7,transaction,{'amount': 25.14},714,None,25.14
306525,eec70ab28af74a22a4aeb889c0317944,transaction,{'amount': 43.58},714,None,43.58
306526,24f56b5e1849462093931b164eb803b5,transaction,{'amount': 22.64},714,None,22.64
306527,24f56b5e1849462093931b164eb803b5,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,fafdcd668e3743c1bb461111dcafc2a4,NaN
306528,5ca2620962114246ab218fc648eb3934,transaction,{'amount': 2.2},714,None,2.20
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.5899999999999999},714,None,1.59
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714,None,9.53
306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714,None,3.61
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.5300000000000002},714,None,3.53
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714,None,4.05

In [6]:
import pandas as pd

# --- Load all datasets ---
customers_df = pd.read_csv("cleaned_customer.csv")
events_df = pd.read_csv("cleaned_events_finally.csv")
offers_df = pd.read_csv("cleaned_offers.csv")

# --- Merge datasets ---
# 1️⃣ Merge offers → events (on offer_id)
merged_df = pd.merge(events_df, offers_df, on="offer_id", how="left")

# 2️⃣ Merge the result → customers (on customer_id)
merged_df = pd.merge(merged_df, customers_df, on="customer_id", how="left")

# --- Optional Cleaning ---
# Replace missing numeric values with 0 and fill blanks for clarity
numeric_cols = merged_df.select_dtypes(include="number").columns
merged_df[numeric_cols] = merged_df[numeric_cols].fillna(0)
merged_df = merged_df.fillna("Unknown")

# --- Save final dataset ---
merged_df.to_csv("merged_final.csv", index=False)

print("✅ Merge complete! File saved as 'merged_final.csv'")
print("Final Columns:")
print(merged_df.columns.tolist())

✅ Merge complete! File saved as 'merged_final.csv'
Final Columns:
['customer_id', 'event', 'value', 'time', 'offer_id', 'amount', 'offer_type', 'difficulty', 'reward', 'duration', 'channels', 'email', 'mobile', 'social', 'web', 'became_member_on', 'age', 'income']

,customer_id,event,value,time,offer_id,amount
306484,a4c2dd694269444085976f10b9b225f6,transaction,{'amount': 28.58},714,None,NaN
306485,4b59509988d34c7298119a840c946453,transaction,{'amount': 0.06},714,None,NaN
306486,92153f7cdda8486b9a2214ceb11b1a17,transaction,{'amount': 4.39},714,None,NaN
306487,3c88696ac23741cb8a709d656fe5ccdf,transaction,{'amount': 25.76},714,None,NaN
306488,1b24e887d980450497b631d8756128e6,transaction,{'amount': 0.35000000000000003},714,None,NaN
306489,1c71315203b746b786c43ce12d7e97fe,transaction,{'amount': 20.84},714,None,NaN
306490,abc4359eb34e4e2ca2349da2ddf771b6,offer viewed,{'offer id': '3f207df678b143eea3cee63160fa8bed'},714,3f207df678b143eea3cee63160fa8bed,NaN
306491,693082e8ccf9458a88c428779cf556a6,transaction,{'amount': 2.16},714,None,NaN
306492,d4f6205a98b4420082aae16e5a93655a,transaction,{'amount': 1.22},714,None,NaN
306493,7b2939e61c324b2087328c4b6fee2632,transaction,{'amount': 26.41},714,None,NaN
306494,e110e63527c24ad1b482f76acde24a42,transaction,{'amount': 20.89},714,None,NaN
306495,5bc03149267147edbcd6a778742b708b,transaction,{'amount': 32.23},714,None,NaN
306496,a6f84f4e976f44508c358cc9aba6d2b3,transaction,{'amount': 6.49},714,None,NaN
306497,a6f84f4e976f44508c358cc9aba6d2b3,offer completed,{'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2...,714,2298d6c36e964ae4a3e7e9706d1fb8c2,NaN
306498,a62b73003f084ae4ae59c4b0e617f647,transaction,{'amount': 19.03},714,None,NaN
306499,197a4afbf77245cfa84c0a4659f47c48,transaction,{'amount': 25.65},714,None,NaN
306500,f0ffaed9279946f1bc29614a234f1ee1,transaction,{'amount': 1.43},714,None,NaN
306501,93907d06a946424ba630487fe7aeafd1,transaction,{'amount': 28.03},714,None,NaN
306502,588ceea482344c3ab6845c83aaed4ac0,transaction,{'amount': 1.08},714,None,NaN
306503,a97208c5be42445d9949e82e0f70f622,transaction,{'amount': 5.8},714,None,NaN
306504,8524d450673b4c24869b6c94380006de,transaction,{'amount': 4.89},714,None,NaN
306505,b895c57e8cd047a8872ce02aa54759d6,transaction,{'amount': 4.48},714,None,NaN
306506,b895c57e8cd047a8872ce02aa54759d6,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,fafdcd668e3743c1bb461111dcafc2a4,NaN
306507,8dda575c2a1d44b9ac8e8b07b93d1f8e,offer viewed,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},714,0b1e1539f2cc45b7b9fa7c272da2e1d7,NaN
306508,8431c16f8e1d440880db371a68f82dd0,transaction,{'amount': 1.19},714,None,NaN
306509,8431c16f8e1d440880db371a68f82dd0,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,fafdcd668e3743c1bb461111dcafc2a4,NaN
306510,ba620885e51c4b0ea64a4f61daad494f,transaction,{'amount': 14.31},714,None,NaN
306511,a1a8f40407c444cc848468275308958a,transaction,{'amount': 2.37},714,None,NaN
306512,8d80970192fa496f99d6b45c470a4b60,transaction,{'amount': 6.92},714,None,NaN
306513,bde275066f3c4fa0bff3093e3b866a2c,transaction,{'amount': 12.73},714,None,NaN
306514,f1e4fd36e5a0446f83861308bddf6945,transaction,{'amount': 8.2},714,None,NaN
306515,0b64be3b241c4407a5c9a71781173829,transaction,{'amount': 2.6},714,None,NaN
306516,86d03d35d7e0434b935e7743e83be3a0,transaction,{'amount': 9.2},714,None,NaN
306517,3408fd05c781401f8442fb6dbaaea9c7,transaction,{'amount': 11.7},714,None,NaN
306518,1593d617fac246ef8e50dbb0ffd77f5f,transaction,{'amount': 40.67},714,None,NaN
306519,f1b31d07b5d84f69a2d5f1d07843989e,transaction,{'amount': 31.13},714,None,NaN
306520,2ce987015ec0404a97ba333e8e814090,transaction,{'amount': 1.6400000000000001},714,None,NaN
306521,2e33545f0a764d27b2ccff95fc8d72c4,transaction,{'amount': 17.35},714,None,NaN
306522,d1c4500ace2e45e9a45d3cd2fccac8d8,transaction,{'amount': 4.42},714,None,NaN
306523,b65affd9e07346a1906364a396950e3d,transaction,{'amount': 18.35},714,None,NaN
306524,d613ca9c59dd42f497bdbf6178da54a7,transaction,{'amount': 25.14},714,None,NaN
306525,eec70ab28af74a22a4aeb889c0317944,transaction,{'amount': 43.58},714,None,NaN
306526,24f56b5e1849462093931b164eb803b5,transaction,{'amount': 22.64},714,None,NaN
306527,24f56b5e1849462093931b164eb803b5,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,fafdcd668e3743c1bb461111dcafc2a4,NaN
306528,5ca2620962114246ab218fc648eb3934,transaction,{'amount': 2.2},714,None,NaN
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.5899999999999999},714,None,NaN
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714,None,NaN
306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714,None,NaN
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.5300000000000002},714,None,NaN
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714,None,NaN